import * as theme from './colorsWideChat';

//Important colors and colors for status symbols(i.e online /offline)
export const COLOR_WHITE = theme.COLOR_WHITE
export const COLOR_PRIMARY = theme.COLOR_PRIMARY
export const COLOR_DANGER = theme.COLOR_DANGER
export const COLOR_SUCCESS = theme.COLOR_SUCCESS
export const STATUS_COLORS = theme.STATUS_COLORS

//colors relating to most text and titles
export const COLOR_TITLE = theme.COLOR_TITLE
export const COLOR_TITLE_HEADER_BUTTON = theme.COLOR_TITLE_HEADER_BUTTON
export const COLOR_TEXT = theme.COLOR_TEXT
export const COLOR_TEXT_DESCRIPTION = theme.COLOR_TEXT_DESCRIPTION
export const COLOR_TYPING = theme.COLOR_TYPING
export const COLOR_UNREAD = theme.COLOR_UNREAD

//Colors relating to buttons
export const COLOR_BUTTON_PRIMARY = theme.COLOR_BUTTON_PRIMARY
export const COLOR_BUTTON_PRIMARY_LOGIN = theme.COLOR_BUTTON_PRIMARY_LOGIN // for login buttons only
export const COLOR_BUTTON_SECONDARY = theme.COLOR_BUTTON_SECONDARY
export const COLOR_BUTTON_SECONDARY_LOGIN = theme.COLOR_BUTTON_SECONDARY_LOGIN //for login buttons only
export const COLOR_BUTTON_TEXT_PRIMARY = theme.COLOR_BUTTON_TEXT_PRIMARY
export const COLOR_BUTTON_TEXT_PRIMARY_LOGIN = theme.COLOR_BUTTON_TEXT_PRIMARY_LOGIN
export const COLOR_BUTTON_TEXT_SECONDARY = theme.COLOR_BUTTON_TEXT_SECONDARY
export const COLOR_BUTTON_TEXT_SECONDARY_LOGIN = theme.COLOR_BUTTON_TEXT_SECONDARY_LOGIN

//Colors relating to backgrounds and borders
export const COLOR_BACKGROUND_CONTAINER = theme.COLOR_BACKGROUND_CONTAINER
export const COLOR_BACKGROUND_LIST = theme.COLOR_BACKGROUND_LIST
export const COLOR_BACKGROUND_CONTAINER_PRIMARY = theme.COLOR_BACKGROUND_CONTAINER_PRIMARY
export const LOADING_SCREEN_BACKGROUND = theme.LOADING_SCREEN_BACKGROUND
export const COLOR_SEPARATOR = theme.COLOR_SEPARATOR
export const COLOR_BORDER = theme.COLOR_BORDER
export const COLOR_BORDER_SECONDARY = theme.COLOR_BORDER_SECONDARY
export const COLOR_TOAST = theme.COLOR_TOAST
export const COLOR_LOADING = theme.COLOR_LOADING

//Colors related to header/ status bar
export const HEADER_BACKGROUND = theme.HEADER_BACKGROUND
export const HEADER_TITLE = theme.HEADER_TITLE
export const HEADER_BACK = theme.HEADER_BACK
export const HEADER_GRADIENT = theme.HEADER_GRADIENT

//Colors related to drop down sort tab for roomslist
export const COLOR_DROPDOWN_CONTAINER_HEADER = theme.COLOR_DROPDOWN_CONTAINER_HEADER //sort bar for chat channels
export const COLOR_BUTTON_DISABLED = theme.COLOR_BUTTON_DISABLED
export const COLOR_ROOMS_ACTION_BUTTON = theme.COLOR_ROOMS_ACTION_BUTTON
export const COLOR_GROUP_TITLE_CONTAINER = theme.COLOR_GROUP_TITLE_CONTAINER
export const COLOR_GROUP_TITLE = theme.COLOR_GROUP_TITLE
export const COLOR_GROUP_SORT_ICON = theme.COLOR_GROUP_SORT_ICON
export const COLOR_GROUP_SORT_ICON_HEADER = theme.COLOR_GROUP_SORT_ICON_HEADER
export const COLOR_SAFE_AREA_BACKGROUND = theme.COLOR_SAFE_AREA_BACKGROUND
export const COLOR_SEARCHBOX_CONTAINER = theme.COLOR_SEARCHBOX_CONTAINER
export const COLOR_SEARCHBOX_BACKGROUND = theme.COLOR_SEARCHBOX_BACKGROUND
export const COLOR_SEARCHBOX_TEXT = theme.COLOR_SEARCHBOX_TEXT
export const COLOR_TEXT_INPUT_BACKGROUND = theme.COLOR_TEXT_INPUT_BACKGROUND
export const COLOR_TEXT_HEADER = theme.COLOR_TEXT_HEADER
export const COLOR_TEXT_DROPDOWN_CONTAINER = theme.COLOR_TEXT_DROPDOWN_CONTAINER
export const COLOR_ITEM_CURRENT = theme.COLOR_ITEM_CURRENT

//Colors related to linked users / items in chat
export const COLOR_MENTIONED_USER = theme.COLOR_MENTIONED_USER
export const COLOR_BACKGROUND_MENTIONED_USER = theme.COLOR_BACKGROUND_MENTIONED_USER //transparent
export const COLOR_MENTIONED_LOGGED_USER = theme.COLOR_MENTIONED_LOGGED_USER
export const COLOR_BACKGROUND_MENTIONED_LOGGED_USER = theme.COLOR_BACKGROUND_MENTIONED_LOGGED_USER
export const COLOR_MENTIONED_USER_ALL = theme.COLOR_MENTIONED_USER_ALL
export const COLOR_BACKGROUND_MENTIONED_USER_ALL = theme.COLOR_BACKGROUND_MENTIONED_USER_ALL
export const COLOR_LINK = theme.COLOR_LINK
export const COLOR_REPLIED_THREAD = theme.COLOR_REPLIED_THREAD
export const COLOR_MESSAGE_THREAD = theme.COLOR_MESSAGE_THREAD
export const COLOR_MESSAGE_THREAD_TEXT = theme.COLOR_MESSAGE_THREAD_TEXT
export const COLOR_LINK_TITLE = theme.COLOR_LINK_TITLE
export const COLOR_REACTIONS = theme.COLOR_REACTIONS
export const COLOR_REACTIONS_COUNT = theme.COLOR_REACTIONS_COUNT
export const COLOR_KEYBOARD_ICONS = theme.COLOR_KEYBOARD_ICONS

//colors in profile view
export const COLOR_AVATAR_BUTTON = theme.COLOR_AVATAR_BUTTON
export const COLOR_DIALOG_INPUT = theme.COLOR_DIALOG_INPUT

//colors related to login
export const COLOR_LOGIN_BACKGROUND_GRADIENT_START = theme.COLOR_LOGIN_BACKGROUND_GRADIENT_START
export const COLOR_LOGIN_BACKGROUND_GRADIENT_END = theme.COLOR_LOGIN_BACKGROUND_GRADIENT_END
export const COLOR_LOGIN_CONTAINER_BACKGROUND = theme.COLOR_LOGIN_CONTAINER_BACKGROUND
export const COLOR_LOGIN_TEXT_BACKGROUND = theme.COLOR_LOGIN_TEXT_BACKGROUND
export const COLOR_LOGIN_TEXT_BORDER = theme.COLOR_LOGIN_TEXT_BORDER
export const COLOR_LOGIN_TEXT = theme.COLOR_LOGIN_TEXT
export const COLOR_LOGIN_SERVICE_TEXT = theme.COLOR_LOGIN_SERVICE_TEXT
